const ApiUrl = {
    SIGNIN: 'register',
    Login: 'login',
    Country: 'country',
    ChangePassword: 'change-password',
    Logout: 'logout',
    Otp: 'otp-verify',
    ResendOtp: 'resend-otp-verify',
    Specification: 'specification',
    GATPROFILE: 'user-profile',
    ForgotPassword: 'forgor-password',
    forgotOtpMatch: 'forgor-otp-verify',
    forgotOtpResend: 'forgor-password',
    SetNewPassword: 'set-new-password',
    UpdateProfile: 'profile-update',
    FilterUniversity: 'university-filter',
    UniversityDetails: 'university-detail',
    DownloadDocument: 'download-document',
    UploadDocument: 'upload-document',
    GetUploadDocument: 'get-upload-document',
    UpdateDocument: 'edit-upload-document',
    NotificationList: 'notification',
    MessageList:'message',
    SendMeaasge:'message-send',
    DocumentRequest: 'document-request',
}
export default ApiUrl