const images = {
  TopImage: require("../assets/Images/topImage.png"),
  MailIcon: require("../assets/Images/mail.png"),
  Password: require("../assets/Images/password.png"),
  RightIcon: require("../assets/Images/rightIcon.png"),
  userIcon: require("../assets/Images/userIcon.png"),
  fUser: require("../assets/Images/fUser.png"),
  woman_with: require("../assets/Images/woman_with.png"),
  Calendar: require("../assets/Images/Calendar.png"),
  phoneIcon: require("../assets/Images/phoneIcon.png"),
  couIcon: require("../assets/Images/couIcon.png"),
  mortarboard: require("../assets/Images/mortarboard.png"),
  downArray: require("../assets/Images/asdsd.png"),
  asdsd: require("../assets/Images/asdsd.png"),
  University_logo: require("../assets/Images/University_logo.png"),
  details: require("../assets/Images/details.png"),
  location: require("../assets/Images/location.png"),
  country_id: require("../assets/Images/country_id.png"),
  city_icon: require("../assets/Images/city_icon.png"),
  email_id: require("../assets/Images/email_id.png"),




  trophy: require("../assets/Images/trophy.png"),
  Research: require("../assets/Images/Research.png"),
  Status: require("../assets/Images/Status.png"),
  student: require("../assets/Images/student.png"),
  Total: require("../assets/Images/Total.png"),
  Scholarships: require("../assets/Images/Scholarships.png"),
  collage: require("../assets/Images/collage.png"),
  happylogo: require("../assets/Images/happylogo.png"),
  form: require("../assets/Images/form.png"),
  uploadIcon: require("../assets/Images/uploadIcon.png"),
  ic_archive: require("../assets/Images/ic_archive.png"),
  kycForm: require("../assets/Images/kycForm.png"),
  regiForm: require("../assets/Images/regiForm.png"),
  fornOne: require("../assets/Images/fornOne.png"),
  left_arrow: require("../assets/Images/left_arrow.png"),
  menu: require("../assets/Images/menu.png"),
  user: require("../assets/Images/user.png"),
  camera: require("../assets/Images/camera.png"),
  Student_Profil: require("../assets/Images/Student_Profil.png"),
  profileImg: require("../assets/Images/profileImg.png"),
  passHide: require("../assets/Images/passHide.png"),
  passShow: require("../assets/Images/passShow.png"),
  woman_withact: require("../assets/Images/woman_withact.png"),
  mailDic: require("../assets/Images/mailDic.png"),
  Calendaract: require("../assets/Images/Calendaract.png"),
  phoneiconAct: require("../assets/Images/phoneiconAct.png"),
  houseAct: require("../assets/Images/houseAct.png"),
  housee: require("../assets/Images/housee.png"),
  passwordAct: require("../assets/Images/passwordAct.png"),
  drawer: require("../assets/Images/drawer.png"),
  home: require("../assets/Images/home.png"),
  terma: require("../assets/Images/terma.png"),
  polici: require("../assets/Images/polici.png"),
  profileSetting: require("../assets/Images/profileSetting.png"),
  changePass: require("../assets/Images/changePass.png"),
  logout: require("../assets/Images/logout.png"),
  otpIcon: require("../assets/Images/otpIcon.png"),
  pdf: require("../assets/Images/pdf.png"),
  upload: require("../assets/Images/upload.png"),
  delete: require("../assets/Images/delete.png"),
  notification: require("../assets/Images/notification.png"),
  send: require("../assets/Images/send.png"),
  refresh: require("../assets/Images/refresh.png"),
  ic_launcher: require("../assets/Images/ic_launcher.png"),




  check_icon: require("../assets/Images/check_icon.png"),
  w45ve: require("../assets/Images/w45ve.png"),
  add_new_card: require("../assets/Images/add_new_card.png"),
  circle_checked_icon: require("../assets/Images/circle_checked_icon.png"),
  deleteIcon: require('../../src/assets/Images/delete1.png'),

};

export default images;
